name: Build and deploy JAR app to Azure Web App - mwo3-pipelines

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Build Number
        run: echo "BUILD_NUMBER=0.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven and run tests
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy-development:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.event.action != 'closed'
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'mwo3-dev'
          slot-name: 'Production'
          package: '*.jar'
          publish-profile: ${{ secrets.AZURE_PUBLISH_DEVELOPMENT }}


  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-development
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.event.action != 'closed'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'mwo3-pipelines'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PRODUCTION }}
          package: '*.jar'

